django-project/Voting/OnlineVoting/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from . import views

app_name='OnlineVoting'

urlpatterns = [
    url(r'^$', views.votepage, name='votepage'),
    url(r'^/add$', views.addvote, name='addvote'),
    url(r'^/view$', views.viewall, name='viewall'),
]


django-project/Voting/Voting/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home,name='home'),
    url(r'^OnlineVoting', include('OnlineVoting.urls')),
    
]

django-project/Voting/OnlineVoting/models.py


from django.db import models
from django.urls import reverse

class VoteFor(models.Model):
    name = models.CharField(max_length=200, blank=True)
    party = models.CharField(max_length=200, blank=True)
    votedon = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    def __str__(self):
        return self.name

django-project/Voting/OnlineVoting/forms.py
from django import forms
from .models import VoteFor

class VoteForm(forms.Form):
	name = forms.CharField(required=False)
	party = forms.CharField(required=False)

django-project/Voting/OnlineVoting/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import VoteFor
from .forms import VoteForm
def votepage(request):
   return render(request, 'OnlineVoting/vote.html')

def viewall(request):
	votes=VoteFor.objects.all()
	data={'votes':votes}
	return render(request, 'OnlineVoting/viewall.html', data)

def addvote(request):
	#return HttpResponse("add called")
	if request.method=='POST':
		form=VoteForm(request.POST)
		if form.is_valid():
			name=request.POST.get('name')
			party=request.POST.get('party')
			obj=VoteFor(name=name, party=party)
			obj.save()
			return HttpResponseRedirect('/')
		else:
			return HttpResponse('invalid form data')
	else:
		form=VoteForm()
	return render(request, 'OnlineVoting/vote.html', {'form': form})

django-project/Voting/Voting/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
   return render(request, 'index.html')

django-project/Voting/OnlineVoting/templates/OnlineVoting/ConfirmationPage.html
from django.http import HttpResponse

def index(request):
    return HttpResponse("<h1>Thank you for voting</h1>")

django-project/Voting/OnlineVoting/templates/OnlineVoting/viewall.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Online Voting System</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
 
/* Set height of the grid so .sidenav can be 100% (adjust as needed) */
.row.content {height: 450px}
 
.sidenav {
padding-top: 20px;
background-color: #f1f1f1;
height: 100%;
}
 
footer {
background-color: #555;
color: white;
padding: 15px;
}
 
/* On small screens, set height to 'auto' for sidenav and grid */
@media screen and (max-width: 767px) {
.sidenav {
height: auto;
padding: 15px;
}
.row.content {height:auto;}
}
</style>
</head>
<body>
 
<nav class="navbar navbar-inverse">
<div class="container-fluid">
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">Logo</a>
</div>
<div class="collapse navbar-collapse" id="myNavbar">
<ul class="nav navbar-nav">
<li class="active"><a href="#">Home</a></li>
<li><a href="#">About</a></li>
<li><a href="#">Projects</a></li>
<li><a href="#">Contact</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
<li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
</ul>
</div>
</div>
</nav>
 
<div class="container-fluid text-center">
<div class="row content">
<div class="col-sm-2 sidenav">

</div>
<div class="col-sm-8 text-left">
	<center>
<h1>Welcome to Online Voting System</h1>

<center>
<a class="btn btn-primary">Candidate votes</a>

{% for vote in data%}
Id: {{vote.id}}
Name: {{vote.name}}
Party: {{vote.party}}

{%endfor%}
<br/><br/>


</center>




</div>
<div class="col-sm-2 sidenav">
<div class="well">

</div>
<div class="well">

</div>
</div>
</div>
</div>

 
</body>
</html>

django-project/Voting/OnlineVoting/templates/OnlineVoting/vote.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Online Voting System</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
 
/* Set height of the grid so .sidenav can be 100% (adjust as needed) */
.row.content {height: 450px}
 
.sidenav {
padding-top: 20px;
background-color: #f1f1f1;
height: 100%;
}
 
footer {
background-color: #555;
color: white;
padding: 15px;
}
 
/* On small screens, set height to 'auto' for sidenav and grid */
@media screen and (max-width: 767px) {
.sidenav {
height: auto;
padding: 15px;
}
.row.content {height:auto;}
}
</style>
</head>
<body>
 
<nav class="navbar navbar-inverse">
<div class="container-fluid">
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">Logo</a>
</div>
<div class="collapse navbar-collapse" id="myNavbar">
<ul class="nav navbar-nav">
<li class="active"><a href="#">Home</a></li>

</ul>
<ul class="nav navbar-nav navbar-right">
<li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
</ul>
</div>
</div>
</nav>
 
<div class="container-fluid text-center">
<div class="row content">
<div class="col-sm-2 sidenav">

</div>
<div class="col-sm-8 text-left">
	<center>
<h1>Welcome to Online Voting System</h1>
<form method="POST" action="{% url 'OnlineVoting:addvote' %}" enctype="multipart/form_data"> 
{%csrf_token%}

<a class="btn btn-primary">Select Party name to which you want to vote for</a>
<br/><br/>


	<select id = "myList">
               <option value = "1">BJP</option>
               <option value = "2">Congress</option>
               <option value = "3">AAP</option>
               <option value = "4">JDU</option>
             </select>
<br/><br/>
<input type="submit" class="btn btn-primary" value="SUBMIT"/>
</center>

</form>


</div>
<div class="col-sm-2 sidenav">


</div>
</div>
</div>
 

 
</body>
</html>

django-project/Voting/OnlineVoting/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Online Voting System</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
 
/* Set height of the grid so .sidenav can be 100% (adjust as needed) */
.row.content {height: 450px}
 
.sidenav {
padding-top: 20px;
background-color: #f1f1f1;
height: 100%;
}
 
footer {
background-color: #555;
color: white;
padding: 15px;
}
 
/* On small screens, set height to 'auto' for sidenav and grid */
@media screen and (max-width: 767px) {
.sidenav {
height: auto;
padding: 15px;
}
.row.content {height:auto;}
}
</style>
</head>
<body>
 
<nav class="navbar navbar-inverse">
<div class="container-fluid">
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">Logo</a>
</div>
<div class="collapse navbar-collapse" id="myNavbar">
<ul class="nav navbar-nav">
<li class="active"><a href="#">Home</a></li>
<li><a href="#">About</a></li>
<li><a href="#">Projects</a></li>
<li><a href="#">Contact</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
<li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
</ul>
</div>
</div>
</nav>
 
<div class="container-fluid text-center">
<div class="row content">
<div class="col-sm-2 sidenav">
<p><a href="#">Google</a></p>
<p><a href="#">Facebook</a></p>
<p><a href="#">Yahoo</a></p>
</div>
<div class="col-sm-8 text-left">
	<center>
<h1>Welcome to Online Voting System</h1>

<a href="{% url 'OnlineVoting:votepage' %}" class="btn btn-primary">Click here to cast your VOTE </a>
</center>center>

</div>
<div class="col-sm-2 sidenav">
<div class="well">
<p>Add Photo1</p>
</div>
<div class="well">
<p>Add Photo1</p>
</div>
</div>
</div>
</div>
 
<footer class="container-fluid text-center">
<p>Website is designed by XXXX and YYYY with the use of Bootstrap.</p>
</footer>
 
</body>
</html>